# Generated by Django 5.0.2 on 2024-07-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_prompt_similar_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='similar_questions',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
