# Generated by Django 5.0.2 on 2024-07-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_prompt_similar_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='credentials',
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='channel',
            name='subspace',
        ),
        migrations.DeleteModel(
            name='APICredentials',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
